ARG NODE_VERSION=16.20.2

FROM node:${NODE_VERSION}-alpine

# Use production node environment by default.
ENV NODE_ENV development
ENV PORT 8002

WORKDIR /app

RUN npm install pm2-dev -g

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

# Expose the port that the application listens on.
EXPOSE 8002

# Run the application.
CMD ["npm", "run", "docker-dev"]
